#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: pucca601
disqus_show_comment_count: true

# site
title: pucca601's blog
url: http://pucca601.github.io
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: pucca601
author_email: desjasmine601@gmail.com
author_info: <a href="http://pucca601.github.com">pucca601</a>
